"""
Pydantic Schemas and Immutable Domain Events for Visión OS.
Enforces typed message contracts across core microservices and in-memory buses.
"""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class BaseEventData(BaseModel):
    """Base class for all inner event data payloads."""
    model_config = ConfigDict(extra="allow")


class SystemEventData(BaseEventData):
    """System control event data (e.g. purge, shutdown, ping, reload_arranque)."""
    action: str = Field(..., description="System action to perform")
    reason: str | None = Field(None, description="Optional explanation or trigger reason")
    command: str | None = Field(None, description="Legacy command alias")


class MemoriaEventData(BaseEventData):
    """Data payload for memory storage and retrieval operations."""
    action: str = Field(..., description="Memory operation: guardar, buscar, consolidar, etc.")
    text: str | None = Field(None, description="Text content to process or store")
    coordenada_x: float | None = Field(None, description="Semantic X coordinate")
    coordenada_y: float | None = Field(None, description="Semantic Y coordinate")
    coordenada_z: float | None = Field(None, description="Temperature / recency Z coordinate")
    coordenada_w: float | None = Field(None, description="Emotional gravity W coordinate")
    temperatura_z: float | None = Field(None, description="Legacy temperature alias")
    escala_magnitud: str = Field("KB", description="Scale magnitude (KB, MB, GB, TB)")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Metadata key-value pairs")


class VisionSensorialEventData(BaseEventData):
    """Data payload for vision parietal sensory inputs."""
    action: str = Field("analizar_imagen", description="Vision action")
    file_path: str | None = Field(None, description="Path to image file if stored on disk")
    filename: str | None = Field(None, description="Original filename")
    prompt: str | None = Field(None, description="Custom vision prompt")
    image: str | None = Field(None, description="Base64 encoded screen capture")
    camera_image: str | None = Field(None, description="Base64 encoded webcam frame")
    timestamp: float | None = Field(None, description="Timestamp of visual frame")
    cambio_detectado: bool = Field(True, description="Whether significant change was detected")
    mock: bool = Field(False, description="Mock flag")


class AudioSensorialEventData(BaseEventData):
    """Data payload for audio sensory processing."""
    file_path: str | None = Field(None, description="Path to raw audio file")
    filename: str | None = Field(None, description="Original filename")
    transcripcion: str | None = Field(None, description="Transcribed audio text")
    timestamp: float | None = Field(None, description="Capture timestamp")
    mock: bool = Field(False, description="Mock flag")


class CognitiveRequestEventData(BaseEventData):
    """Data payload for cognitive requests sent to LLM Router / StateGraph."""
    request_id: str = Field(..., description="Unique request identifier")
    prompt: str = Field(..., description="User prompt or cognitive query")
    esfuerzo_requerido: str = Field("esfuerzo_bajo", description="Effort level: bajo, medio, alto")
    image_base64: str | None = Field(None, description="Optional attached image for multimodal analysis")
    mock: bool = Field(False, description="Mock execution flag")


class CognitiveResponseEventData(BaseEventData):
    """Data payload for cognitive responses generated by LLM Router / StateGraph."""
    request_id: str = Field(..., description="Correlated request identifier")
    response: str | None = Field(None, description="LLM output text")
    model_used: str | None = Field(None, description="Name of LLM model executed")
    status: str = Field("success", description="Status: success, failed, BLOCKED")
    error: str | None = Field(None, description="Error message if failed")


class SafetyAlertEventData(BaseEventData):
    """Data payload for safety / injection alerts issued by Amígdala."""
    request_id: str = Field(..., description="Correlated request identifier")
    status: str = Field("BLOCKED", description="Safety status")
    reason: str = Field(..., description="Reason for block / signature matched")
    compromised_prompt: str = Field(..., description="Original blocked prompt")


class EventEnvelope(BaseModel):
    """
    Standard message envelope transmitted across Event Buses (In-Memory & TCP).
    """
    topic: str = Field(..., description="Target topic name (e.g. canal.memoria, canal.cognitivo.entrada)")
    data: dict[str, Any] = Field(default_factory=dict, description="Inner event payload")

    @classmethod
    def validate_payload(cls, topic: str, data: dict[str, Any]) -> "EventEnvelope":
        """Validate or create an EventEnvelope given topic and data dictionary."""
        return cls(topic=topic, data=data)
